# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

pinning-strategy = "latest-up"
run-post-link-scripts = "false" # set to "insecure" to allow running post-link scripts
