version: v2025.07.0
tutorial: false
logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'
remote:
  ssh: ''
  path: ''
run:
  name: ''
  prefix: ''
  scenarios:
    enable: false
    file: config/scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: false
