# yaml-language-server: $schema=../schema.json
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0
run:
  name: "distribution-grid-experimental"

electricity:
  voltages: [63., 66., 90., 110., 132., 150., 220., 300., 330., 380., 400., 500., 750.]
  base_network: osm

transmission_projects:
  enable: false

data:
  osm:
    source: build
    version: unknown

# Please provide your own user agent details when using the Overpass API
overpass_api:
  url: https://overpass-api.de/api/interpreter
  max_tries: 5
  timeout: 600
  user_agent:
    project_name: PyPSA-Eur
    email: contact@pypsa.org
    website: https://github.com/PyPSA/pypsa-eur
